#!/usr/bin/env sh

set -e

rm -rf build docs
mkdir -p build docs

npx pug src -o build
npx stylus src -c -o build
cp src/*.js build
npx inline-source --compress --root build build/index.html docs/index.html

rm -rf build

cp static/* docs
